apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    appName: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  namespace: roboshop
  labels:
   appName: catalogue
spec:
  containers:
    - name: catalogue
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
      env:
        - name: MONGO_URL
          value: "mongodb://mongo.dev.naifah.online:27017/catalogue"
        - name: MONGO
          value: "true" 

---

apiVersion: batch/v1
kind: Job
metadata:
  name: catalogue
  namespace: roboshop
  labels:
   appName: catalogue
spec:
  template:
    spec:
      containers:
      - name: catalogue
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
        env:
        - name: DB_TYPE 
          value: mongo
        - name: APP_GIT_URL 
          value: https://github.com/roboshop-devops-project-v3/catalogue
        - name: DB_HOST
          value: mongo.dev.naifah.online
        - name: SCHEMA_FILE
          value: db/master-data.js
      restartPolicy: Never
  backoffLimit: 4


  #DB_TYPE=mongo -e APP_GIT_URL=https://github.com/roboshop-devops-project-v3/catalogue -e DB_HOST=mongo-ip -e SCHEMA_FILE=db/master-data.js