apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    appName: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---

apiVersion: v1
kind: Pod
metadata:
  name: user
  namespace: roboshop
  labels:
   appName: user
spec:
  containers:
    - name: user
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/user
      env:
        - name: MONGO_URL
          value: "mongodb://mongo-redis.dev.naifah.online:27017/users"
        - name: MONGO
          value: "true"
        - name: REDIS_URL
          value: "redis://redis-redis.dev.naifah.online:6379"

#
#dnf install docker -y
#docker run -d -p 8080:8080 -e MONGO=true -e MONGO_URL="mongodb://mongo-ip:27017/users" -e REDIS_URL="redis://redis-ip:6379" public.ecr.aws/w8x4g9h7/roboshop-v3/user
