apiVersion: apps/v1
kind: Deploymnet
metadata:
  name: deploy-01
  labels:
    app: nginx
spec:                                      
  # modify replicas according to your case
  replicas: 1      
  selector:       
    matchLabels:
      app: nginx
  template:      
    metadata:
      labels:
        app: nginx
    spec:                  
      containers:              
      - name: nginx
        image: docker.io/nginx:1.20