apiVersion: v1
kind: Pod
metadata:
  name: Pod-07
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      env:
    - name: DCATALOGUE_HOST
      value: "Hello World"

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: cm-07
data:
  # property-like keys; each key maps to a simple value
  CATALOGUE_HOST: "catalogue"
  CART_HOST: "cart"
 


#### A ConfigMap is an API object that lets you store configuration for other objects to use. The data field is designed to contain UTF-8 strings while the binaryData field is designed to contain binary data as base64-encoded strings.

---
apiVersion: v1
kind: Pod
metadata:
  name: Pod-07-cm
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      env:
    - name: CATALOGUE_HOST
      valueFrom:
      configMapKeyRef:
              name: cm-07       # The ConfigMap this value comes from.
              key:  CATALOGUE_HOST 
    - name: CART_HOST
      valueFrom:
      configMapKeyRef:
              name: cm-07       # The ConfigMap this value comes from.
              key:  CART_HOST

---
apiVersion: v1
kind: Pod
metadata:
  name: Pod-07-cm-1
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      envFrom:                                    #####all the values from the file. Attach the config to all file.
      - configMapRef:   
            name: cm-07   ### name of the configmap

#### config mount

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-07-file
data:
  catalogue.service: |
    [Unit]
    Description = Catalogue Service

    [Service]
    User=roboshop
    Environment=MONGO={{ secrets.MONGO }}
    Environment=MONGO_URL="{{ secrets.MONGO_URL }}"
    ExecStart=/bin/node /app/server.js
    SyslogIdentifier=catalogue

    [Install]
    WantedBy=multi-user.target
---
apiVersion: v1
kind: Pod
metadata:
  name: Pod-07-cm-2
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want, every configfile will become path as/etc/config kubectl exec it pod-07-cm-o1(name of the pod)-- bash then go to the path cd /etc/congig/  ls cat cart.service
        # to add to the container
        name: cm-07-file

####Next topic is secrets it same as mount:  Secret is an object that contains a small amount of sensitive data such as a password, a token, or a key.

apiVersion: v1
kind: Secret
metadata:
  name: secret07-01
data:
   password: abcd1234
---

apiVersion: v1
kind: Pod
metadata:
  name: Pod-07-secret
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      env:
    - name: password
      valueFrom:
      SecretKeyRef:
              name: secret07-01       # The ConfigMap this value comes from.
              key:  password


###ConfigMap sumup  declare data value then  configMapKeyRef configMap volumeMounts secrets





