kind: Pod
metadata:
  name: nginx
  namespace: backend
  labels:
    appType: API
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-only-frontend
  namespace: backend
spec:
  podSelector:
    matchLabels:
      appType: API
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          project: demo
    - podSelector:
        matchLabels:
          appType: UI
    ports:
    - protocol: TCP
      port: 80
  egress:
  - {}